const heroes = [{
    "name": "Laurène",
    "speed": 1,
    "health": 100,
    "power": 5
}, {
    "name": "Dorothée",
    "speed": 8,
    "health": 100,
    "power": 4
}, {
    "name": "Céline",
    "speed": 4,
    "health": 100,
    "power": 5
}, {
    "name": "Léana",
    "speed": 5,
    "health": 100,
    "power": 5
}, {
    "name": "Geneviève",
    "speed": 3,
    "health": 100,
    "power": 10
}, {
    "name": "Mahélie",
    "speed": 2,
    "health": 100,
    "power": 8
}, {
    "name": "Marie-françoise",
    "speed": 6,
    "health": 100,
    "power": 4
}, {
    "name": "Illustrée",
    "speed": 5,
    "health": 100,
    "power": 10
}, {
    "name": "Styrbjörn",
    "speed": 7,
    "health": 100,
    "power": 10
}, {
    "name": "Réjane",
    "speed": 4,
    "health": 100,
    "power": 1
}];

module.exports = heroes;