const villains = [{
    "name": "Maï",
    "speed": 4,
    "health": 100,
    "power": 9
}, {
    "name": "Méng",
    "speed": 2,
    "health": 100,
    "power": 8
}, {
    "name": "Laurène",
    "speed": 3,
    "health": 100,
    "power": 4
}, {
    "name": "Irène",
    "speed": 5,
    "health": 100,
    "power": 7
}, {
    "name": "Maëlann",
    "speed": 4,
    "health": 100,
    "power": 4
}, {
    "name": "Pélagie",
    "speed": 5,
    "health": 100,
    "power": 10
}, {
    "name": "Léana",
    "speed": 4,
    "health": 100,
    "power": 4
}, {
    "name": "Pénélope",
    "speed": 2,
    "health": 100,
    "power": 3
}, {
    "name": "Marie-noël",
    "speed": 1,
    "health": 100,
    "power": 1
}, {
    "name": "Félicie",
    "speed": 1,
    "health": 100,
    "power": 5
}];

module.exports = villains;